[DRAFT] Gerencia
StructCE/gitbook pull request #115
Opened 2023-02-10 03:30 UTC by DavidsonGM

# O quê foi feito

- Refatoração da seção de gerência para ficar mais limpa
- Adicionada seções sobre algumas gems importantes que não estavam sendo citadas
- Adicionada seção sobre soft skills

# Pendências

-  Faltou colocar as coisas que foram discutidas no [guia da gerência](https://docs.google.com/document/d/1nIkQnn5kthrmBbCDI7K8MqrJhPVagVjzMsLyxDAt-RE/edit?usp=sharing)

2023-03-18 20:24 UTC, artistrea requested changes
Tá um ótimo início de guia de gerência. Tem coisa que vou começar a aplicar que não fazia, inclusive.
Valeu, David! Se não tiver mais tempo pra corrigir, só me avisar.

2023-03-18 20:24 UTC, artistrea commented on execucao/projetos/gerencia/inicio-de-projeto.md
> +# Início do projeto
Seria mais adequado se houvesse aqui as coisas mais relacionadas à gerência do que do código. Uma menção à criação dos repositórios de back e front seria bom, colocando links para arquivos separados que ensinam a configurar os repositórios.

Aqui faria sentido falar da criação do cronograma, decisão da equipe de desenvolvimento, deliberação sobre tecnologias a serem utilizadas, etc.

2023-03-18 20:24 UTC, artistrea commented on execucao/ruby-on-rails/gems.md
> +A gem `sass-rails` parou de receber suporte em Março de 2019. Substitua ela no Gemfile pela gem `sassc-rails`.
São gems usadas somente em rails full stack

```suggestion
```

2023-03-18 20:24 UTC, artistrea commented on execucao/ruby-on-rails/gems.md
> +5. Adicione o trecho de código abaixo ao arquivo `config/application.yml`:
```suggestion
5. Adicione o trecho de código abaixo ao arquivo `config/application.yml.example`:
```

2023-03-18 20:24 UTC, artistrea commented on execucao/ruby-on-rails/gems.md
> +Após configurar a gem Figaro em seu ambiente, **avise os outros membros do projeto** que eles deveram executar os passos 2, 3 e 5 para configurar a gem em seus ambientes!
```suggestion
Após configurar a gem Figaro em seu ambiente, **avise os outros membros do projeto** que eles devem criar um `config/application.yml` baseado no `.example`, colocando as próprias informações ou chaves usadas no projeto.
```

2023-03-18 20:24 UTC, artistrea commented on execucao/ruby-on-rails/gems.md
> +
```suggestion

### Mailjet
Para envios de email, pode ser utilizada a SDK (kit de desenvolvimento de software) que a Mailjet criou para o ruby.

Basta adicionar à gemfile a gem 'mailjet', e configurar os arquivos de `config/{development/production}` da maneira correta (verificar projetos passados sobre `config.action_mailer`)

```

2023-03-20 20:20 UTC, DavidsonGM commented on execucao/projetos/gerencia/guia.md
> +## Montagem de cronograma
É que nessa página eu ia colocar tudo que a gente tinha montado no [guia da gerência](https://docs.google.com/document/d/1nIkQnn5kthrmBbCDI7K8MqrJhPVagVjzMsLyxDAt-RE/edit), mas acabou que não deu pra terminar

2023-03-21 21:31 UTC, artistrea approved these changes
👌

2023-03-21 21:31 UTC, merged